# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=0.1.0
group=com.oovaa8.catto
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Complete And Total Terrain Overhaul (CATTO)
mod_author=oovaa8
mod_id=catto
license=MPL-2.0
credits=Erosion filter by Rune Skovbo Johansen (runevision): https://www.youtube.com/@runevision, https://blog.runevision.com/2026/03/fast-and-gorgeous-erosion-filter.html
description=Overhul of Minecraft's terrain generation to make it much, much larger.
minecraft_version_range=[1.21.1]
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_version=0.109.0+1.21.1
fabric_loader_version=0.16.9

# Forge
forge_version=0
forge_loader_version_range=0

# NeoForge
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
